server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://101.200.81.38:9916/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: devAccount
    password: pw7VS$K



mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://www.eurakserver01.com:7001/eureka/,http://www.eurakserver02.com:7002/eureka/
